apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: airline
  name: create-secrets-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: airline
roleRef:
  kind: Role
  name: create-secrets-role
  apiGroup: rbac.authorization.k8s.io

