apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-creator
  namespace: airline
spec:
  schedule: "0 0 * * *" # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ecr-secret-creator
              image: bitnami/kubectl:latest # Includes AWS CLI
              command:
                - /bin/sh
                - -c
                - |
                  # Fix for missing /var/lib/apt/lists/partial directory
                  mkdir -p /var/lib/apt/lists/partial
                  # Update package lists and install AWS CLI
                  apt-get update && apt-get install -y awscli
                  # Get the current date in YYYY-MM-DD format
                  TODAY=$(date +'%Y-%m-%d')
                  SECRET_NAME="ecr-secret-$TODAY"

                  # Replace the following values with your AWS settings
                  AWS_REGION=us-east-1
                  AWS_ACCOUNT_ID=<aws_account_id>
                  ECR_URL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

                  # Create the Docker registry secret
                  kubectl create secret docker-registry $SECRET_NAME \
                    --namespace=airline \
                    --docker-server=$ECR_URL \
                    --docker-username=AWS \
                    --docker-password=$(aws ecr get-login-password --region $AWS_REGION) \
                    --docker-email=j@j.com
              env:
                - name: AWS_REGION
                  value: us-east-1
                - name: AWS_ACCOUNT_ID
                  value: "<aws_account_id>"
                - name: EMAIL
                  value: j@j.com
              securityContext:
                runAsUser: 0 # Temporarily run as root
                runAsGroup: 0
              envFrom:
                - secretRef:
                    name: aws-credentials # Store AWS credentials as a Kubernetes secret
          restartPolicy: OnFailure

