apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-arrivals
  namespace: airline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-arrivals
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: get-arrivals
    spec:
      containers:
      - image: <aws_acct_id>.dkr.ecr.us-east-1.amazonaws.com/arrivals-service:latest
        imagePullPolicy: Always
        name: get-arrivals
        ports:
        - containerPort: 8082
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ecr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
