apiVersion: v1
data:
  REACT_APP_GOOGLE_MAPS_API_KEY: QUl6YVN5QlRKanJHeHY1bzdyaXdQOTc3V2ZmcHlKTW1KYmc4TFNn
kind: Secret
metadata:
  creationTimestamp: "2025-01-17T22:50:20Z"
  name: google-maps-api-key
  namespace: airline
  resourceVersion: "248699"
  uid: 37cc59c1-6b92-4075-8d97-cc9990f06698
type: Opaque
